<?php
namespace Tests\Feature;
use App\Models\ResearchPublication;
use App\Models\User;
use Database\Seeders\RolesAndPermissionsSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
class ResearchPublicationRepositoryTest extends TestCase
{
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(RolesAndPermissionsSeeder::class);Storage::fake('local');Notification::fake();}
 public function test_researcher_creates_draft_with_primary_author_and_private_pdf():void{$u=$this->researcher();$this->actingAs($u)->post(route('researcher.publications.store'),$this->validData())->assertRedirect()->assertSessionHasNoErrors();$p=ResearchPublication::first();$this->assertSame($u->id,$p->user_id);$this->assertSame('researcher',$p->origin);$this->assertSame('draft',$p->review_status);$this->assertCount(2,$p->authors);$this->assertSame($u->id,$p->authors->first()->user_id);Storage::disk('local')->assertExists($p->pdf_path);$this->assertFalse($p->pdf_public);}
 public function test_user_cannot_create_and_other_researcher_cannot_view_or_download_private_pdf():void{$user=$this->role('USUARIO');$this->actingAs($user)->get(route('researcher.publications.create'))->assertForbidden();$owner=$this->researcher();$this->actingAs($owner)->post(route('researcher.publications.store'),$this->validData());$p=ResearchPublication::first();$other=$this->researcher();$this->actingAs($other)->get(route('researcher.publications.show',$p))->assertForbidden();$this->actingAs($other)->get(route('researcher.publications.pdf',$p))->assertForbidden();}
 public function test_draft_is_private_from_editors_until_researcher_submits_it():void{$owner=$this->researcher();$this->actingAs($owner)->post(route('researcher.publications.store'),$this->validData());$p=ResearchPublication::firstOrFail();$editor=$this->role('WEBMASTER',false);$this->actingAs($editor)->get(route('admin.submissions.index'))->assertOk()->assertDontSee($p->title);$this->actingAs($editor)->get(route('admin.submissions.show',['research_publication',$p->id]))->assertNotFound();$this->actingAs($editor)->get(route('admin.research-publications.edit',$p))->assertForbidden();$this->actingAs($editor)->get(route('admin.submissions.download',['research_publication',$p->id]))->assertNotFound();$this->actingAs($owner)->get(route('researcher.publications.show',$p))->assertOk()->assertSee($p->title);$this->actingAs($owner)->post(route('researcher.publications.submit',$p))->assertRedirect();$this->actingAs($editor)->get(route('admin.submissions.index'))->assertOk()->assertSee($p->title);$this->actingAs($editor)->get(route('admin.submissions.show',['research_publication',$p->id]))->assertOk();}
 public function test_submit_requires_complete_bibliography_and_authorization():void{$u=$this->researcher();$this->actingAs($u)->post(route('researcher.publications.store'),['title'=>'Borrador incompleto']);$p=ResearchPublication::first();$this->actingAs($u)->post(route('researcher.publications.submit',$p))->assertSessionHasErrors();$this->actingAs($u)->put(route('researcher.publications.update',$p),$this->validData())->assertSessionHasNoErrors();$this->actingAs($u)->post(route('researcher.publications.submit',$p))->assertRedirect();$this->assertSame('submitted',$p->fresh()->review_status);$this->actingAs($u)->get(route('researcher.publications.edit',$p))->assertForbidden();}
 public function test_editorial_lifecycle_public_visibility_and_pdf_rules():void{$owner=$this->researcher();$this->actingAs($owner)->post(route('researcher.publications.store'),$this->validData());$p=ResearchPublication::first();$this->actingAs($owner)->post(route('researcher.publications.submit',$p));$editor=$this->role('WEBMASTER',false);$this->actingAs($editor)->get(route('admin.submissions.show',['research_publication',$p->id]))->assertOk();$this->actingAs($editor)->patch(route('admin.submissions.start-review',['research_publication',$p->id]))->assertRedirect();$this->actingAs($editor)->patch(route('admin.submissions.approve',['research_publication',$p->id]))->assertRedirect();$this->actingAs($editor)->put(route('admin.research-publications.update',$p),$this->adminData(['pdf_public'=>1]))->assertSessionHasNoErrors();$this->assertTrue($p->fresh()->pdf_public);$this->actingAs($editor)->patch(route('admin.submissions.publish',['research_publication',$p->id]))->assertRedirect();$p->refresh();$this->get(route('research-publications.index'))->assertSee($p->title);$this->get(route('research-publications.show',$p->slug))->assertOk()->assertSee('Coautora Externa');$this->get(route('research-publications.pdf',$p->slug))->assertOk();$this->actingAs($editor)->patch(route('admin.submissions.unpublish',['research_publication',$p->id]))->assertRedirect();$this->get(route('research-publications.show',$p->slug))->assertNotFound();$this->assertSame('approved',$p->fresh()->review_status);}
 public function test_pdf_cannot_be_made_public_without_distribution_authorization():void{$p=$this->publication($this->researcher(),['review_status'=>'approved','pdf_distribution_authorized'=>false,'pdf_public'=>false]);$editor=$this->role('ADMINISTRADOR');$this->actingAs($editor)->put(route('admin.research-publications.update',$p),$this->adminData(['pdf_public'=>1,'pdf_distribution_authorized'=>0]))->assertSessionHasNoErrors();$this->assertFalse($p->fresh()->pdf_public);}
 public function test_search_filters_and_scope_exclude_non_public_records():void{$u=$this->researcher();$public=$this->publication($u,['title'=>'Inteligencia territorial','slug'=>'inteligencia-territorial','review_status'=>'approved','status'=>'published','published_at'=>now(),'keywords'=>['territorio','innovación','ciencia']]);$this->publication($u,['title'=>'Documento oculto','slug'=>'documento-oculto','review_status'=>'submitted']);$this->get(route('research-publications.index',['search'=>'territorial','type'=>'scientific_article']))->assertSee($public->title)->assertDontSee('Documento oculto');}
 private function validData(array $extra=[]):array{return $extra+['title'=>'Estudio sobre innovación territorial','abstract'=>str_repeat('Resumen científico con suficiente información metodológica. ',3),'publication_type'=>'scientific_article','publication_date'=>'2026-05-10','research_area'=>'Ingeniería y tecnología','research_line'=>'Innovación territorial','institution'=>'Universidad de Prueba','keywords_text'=>'innovación, territorio, ciencia','doi'=>'10.1234/rimis.2026.1','pdf'=>UploadedFile::fake()->create('investigacion.pdf',100,'application/pdf'),'pdf_distribution_authorized'=>1,'authors'=>[['author_name'=>'Investigador Principal','institution'=>'Universidad de Prueba','is_corresponding'=>1],['author_name'=>'Coautora Externa','institution'=>'Instituto Demo','orcid'=>'0000-0000-0000-000X']]];}
 private function adminData(array $extra=[]):array{return $extra+['title'=>'Estudio sobre innovación territorial','abstract'=>str_repeat('Resumen científico con suficiente información metodológica. ',3),'publication_type'=>'scientific_article','publication_date'=>'2026-05-10','research_area'=>'Ingeniería y tecnología','institution'=>'Universidad de Prueba','keywords_text'=>'innovación, territorio, ciencia','doi'=>'10.1234/rimis.2026.1'];}
 private function publication(User $u,array $extra=[]):ResearchPublication{return ResearchPublication::create($extra+['user_id'=>$u->id,'title'=>'Artículo demo','slug'=>'articulo-demo-'.uniqid(),'abstract'=>str_repeat('Resumen científico. ',10),'publication_type'=>'scientific_article','research_area'=>'Ingeniería y tecnología','institution'=>'Universidad Demo','keywords'=>['ciencia','tecnología','innovación'],'origin'=>'researcher','review_status'=>'draft','status'=>'draft']);}
 private function researcher():User{$u=$this->role('INVESTIGADOR');$u->researcherProfile()->create(['country'=>'Ecuador','salutation'=>'Doctor','academic_title'=>'PhD','profession'=>'Investigador','research_area'=>'Ingeniería y tecnología','institution'=>'Universidad de Prueba','phone'=>'0999999999','cv_path'=>'cv.pdf','cv_original_name'=>'cv.pdf','completed_at'=>now()]);return $u;}
 private function role(string $role,bool $verified=true):User{$u=User::factory()->create(['email_verified_at'=>$verified?now():null]);$u->assignRole($role);return $u;}
}
