<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Boletines | RIMIS</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="bg-slate-50 font-sans text-slate-800">
    <x-public-header :menus="$publicMenus" />
    <main class="mx-auto max-w-6xl px-5 py-12"><div class="mb-10"><h1 class="text-4xl font-bold">Boletines</h1><p class="mt-3 text-slate-500">Consulta y descarga las publicaciones periódicas de RIMIS.</p></div>
        <div class="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">@forelse($bulletins as $bulletin)<article class="overflow-hidden rounded-xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">@if($bulletin->coverImage)<a href="{{ route('bulletins.show', $bulletin->slug) }}"><img src="{{ $bulletin->coverImage->publicUrl() }}" class="aspect-[3/4] w-full object-cover" alt="{{ $bulletin->title }}"></a>@else<div class="flex aspect-[3/4] items-center justify-center bg-[var(--rimis-charcoal)] text-white"><i class="fa-solid fa-file-pdf text-7xl text-[var(--rimis-primary)]"></i></div>@endif<div class="p-6"><small class="font-semibold text-[var(--rimis-primary-dark)]">{{ $bulletin->published_at->format('d/m/Y') }}</small><h2 class="mt-2 text-xl font-bold"><a href="{{ route('bulletins.show', $bulletin->slug) }}">{{ $bulletin->title }}</a></h2><p class="mt-3 text-sm leading-6 text-slate-600">{{ Str::limit($bulletin->description, 140) }}</p><a href="{{ route('bulletins.show', $bulletin->slug) }}" class="mt-5 inline-block font-semibold text-[var(--rimis-primary-dark)]">Ver boletín <i class="fa-solid fa-arrow-right ml-1"></i></a></div></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-slate-500 sm:col-span-2 lg:col-span-3">No hay boletines publicados todavía.</div>@endforelse</div><div class="mt-10">{{ $bulletins->links() }}</div>
    </main>
</body></html>
