<x-app-layout>
<x-slot name="header"><h1>Suscripción {{ \App\Models\Subscription::TYPE_LABELS[$subscription->type] }}</h1></x-slot>
<div class="row"><div class="col-lg-8"><div class="card card-primary card-outline"><div class="card-body">
<div class="d-flex align-items-center mb-4">@if($subscription->personal_photo_path || $subscription->institution_logo_path)<img src="{{ Storage::disk('public')->url($subscription->personal_photo_path ?: $subscription->institution_logo_path) }}" alt="{{ $subscription->displayName() }}" class="img-circle elevation-2 mr-3" style="width:90px;height:90px;object-fit:cover">@endif<div><h3 class="mb-1">{{ $subscription->displayName() }}</h3><span class="badge badge-info">{{ \App\Models\Subscription::TYPE_LABELS[$subscription->type] }}</span></div></div>
@if($subscription->isProfessional())
<h5 class="border-bottom pb-2">Datos profesionales</h5><dl class="row"><dt class="col-sm-4">Correo</dt><dd class="col-sm-8">{{ $subscription->email }}</dd><dt class="col-sm-4">Cédula</dt><dd class="col-sm-8">{{ $subscription->national_id }}</dd><dt class="col-sm-4">Título de pregrado</dt><dd class="col-sm-8">{{ $subscription->undergraduate_title }}</dd><dt class="col-sm-4">Títulos de posgrado</dt><dd class="col-sm-8">{{ $subscription->postgraduate_titles ?: '—' }}</dd><dt class="col-sm-4">Funciones de docencia</dt><dd class="col-sm-8">{{ $subscription->teaching_functions }}</dd><dt class="col-sm-4">Funciones de investigación</dt><dd class="col-sm-8">{{ $subscription->current_research_functions }}</dd><dt class="col-sm-4">Actividad investigativa</dt><dd class="col-sm-8">{{ $subscription->research_activity }}</dd><dt class="col-sm-4">Áreas</dt><dd class="col-sm-8">{{ implode(', ', $subscription->research_areas ?? []) }}@if($subscription->other_research_area), {{ $subscription->other_research_area }}@endif</dd><dt class="col-sm-4">Comunidades científicas</dt><dd class="col-sm-8">{{ $subscription->scientific_communities ?: '—' }}</dd><dt class="col-sm-4">ORCID</dt><dd class="col-sm-8">{{ $subscription->orcid ?: '—' }}</dd></dl>
@else
<h5 class="border-bottom pb-2">Datos institucionales</h5><dl class="row"><dt class="col-sm-4">Correo institucional</dt><dd class="col-sm-8">{{ $subscription->email }}</dd><dt class="col-sm-4">Autoridad principal</dt><dd class="col-sm-8">{{ $subscription->principal_authority_name }}</dd><dt class="col-sm-4">Año de creación</dt><dd class="col-sm-8">{{ $subscription->foundation_year }}</dd><dt class="col-sm-4">Tipo</dt><dd class="col-sm-8">{{ $subscription->institution_type === 'Otra' ? $subscription->other_institution_type : $subscription->institution_type }}</dd></dl><h5 class="border-bottom pb-2 mt-4">Solicitante</h5><dl class="row"><dt class="col-sm-4">Nombre</dt><dd class="col-sm-8">{{ $subscription->requester_name }}</dd><dt class="col-sm-4">Función</dt><dd class="col-sm-8">{{ $subscription->requester_position }}</dd><dt class="col-sm-4">Correo</dt><dd class="col-sm-8">{{ $subscription->requester_email }}</dd></dl>
@endif
<h5 class="border-bottom pb-2 mt-4">Ubicación y contacto</h5><dl class="row mb-0"><dt class="col-sm-4">Ubicación</dt><dd class="col-sm-8">{{ $subscription->city }}, {{ $subscription->country }}</dd><dt class="col-sm-4">Teléfonos</dt><dd class="col-sm-8">{{ collect([$subscription->contact_phone,$subscription->main_phone,$subscription->mobile_phone])->filter()->join(' / ') }}</dd></dl>
</div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><p><strong>Estado:</strong> {{ \App\Models\Subscription::STATUS_LABELS[$subscription->status] }}</p>@if($subscription->status==='submitted')<form method="POST" action="{{ route('admin.subscriptions.review',$subscription) }}">@csrf @method('PATCH')<button class="btn btn-primary btn-block">Iniciar revisión</button></form>@elseif($subscription->status==='under_review')<form method="POST" action="{{ route('admin.subscriptions.approve',$subscription) }}">@csrf @method('PATCH')<textarea name="review_notes" class="form-control mb-2" placeholder="Observaciones opcionales"></textarea><button class="btn btn-success btn-block">Aprobar</button></form><hr><form method="POST" action="{{ route('admin.subscriptions.reject',$subscription) }}">@csrf @method('PATCH')<textarea name="review_notes" class="form-control mb-2" required placeholder="Motivo del rechazo"></textarea><button class="btn btn-danger btn-block">Rechazar</button></form>@endif</div></div></div></div>
</x-app-layout>
