<x-app-layout>
    <x-slot name="header"><div class="d-flex justify-content-between align-items-center"><div><h1 class="m-0"><i class="fas fa-book-open text-primary mr-2"></i>Boletines</h1><small class="text-muted">Gestiona publicaciones descargables en PDF.</small></div>@can('bulletins.create')<a href="{{ route('admin.bulletins.create') }}" class="btn btn-primary"><i class="fas fa-plus mr-1"></i> Crear boletín</a>@endcan</div></x-slot>
    @include('admin.partials.content-review-filter', ['model' => \App\Models\Bulletin::class])
    <div class="card card-primary card-outline">
        <div class="card-header"><form class="row"><div class="col-md-6"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Buscar boletín"></div><div class="col-md-3"><select name="status" class="form-control"><option value="">Todos los estados</option><option value="draft" @selected(request('status') === 'draft')>Borradores</option><option value="published" @selected(request('status') === 'published')>Publicados</option></select></div><div class="col-md-3"><button class="btn btn-primary">Filtrar</button></div></form></div>
        <div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Boletín</th><th>PDF</th><th>Estado</th><th>Actualización</th><th class="text-right">Acciones</th></tr></thead><tbody>
            @forelse($bulletins as $item)<tr><td><strong>{{ $item->title }}</strong><small class="d-block text-muted">/boletines/{{ $item->slug }}</small></td><td><i class="fas fa-file-pdf text-danger mr-1"></i>{{ $item->formattedSize() }}</td><td><span class="badge badge-{{ $item->isPublished() ? 'success' : 'secondary' }}">{{ $item->isPublished() ? 'Publicado' : 'Borrador' }}</span></td><td>{{ $item->updated_at->format('d/m/Y H:i') }}</td><td class="text-right text-nowrap">@can('bulletins.publish')<form method="POST" action="{{ $item->isPublished() ? route('admin.bulletins.unpublish', $item) : route('admin.bulletins.publish', $item) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $item->isPublished() ? 'secondary' : 'success' }}" title="{{ $item->isPublished() ? 'Despublicar' : 'Publicar' }}"><i class="fas fa-{{ $item->isPublished() ? 'eye-slash' : 'globe' }}"></i></button></form>@endcan @can('bulletins.edit')<a href="{{ route('admin.bulletins.edit', $item) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i></a>@endcan @can('bulletins.delete')<form method="POST" action="{{ route('admin.bulletins.destroy', $item) }}" class="d-inline" onsubmit="return confirm('¿Eliminar este boletín y su PDF?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form>@endcan</td></tr>@empty<tr><td colspan="5" class="text-center py-5">No hay boletines.</td></tr>@endforelse
        </tbody></table></div></div>
        @if($bulletins->hasPages())<div class="card-footer">{{ $bulletins->links() }}</div>@endif
    </div>
</x-app-layout>
