<x-app-layout><x-slot name="header"><h1 class="m-0"><i class="fas fa-inbox text-primary mr-2"></i>Aportes recibidos</h1></x-slot>
<div class="card"><div class="card-header"><form class="row">
<div class="col-md-2"><select name="type" class="form-control"><option value="">Todos</option><option value="event" @selected(request('type')==='event')>Eventos</option><option value="bulletin" @selected(request('type')==='bulletin')>Boletines</option><option value="call" @selected(request('type')==='call')>Convocatorias</option><option value="research_publication" @selected(request('type')==='research_publication')>Investigaciones</option></select></div>
<div class="col-md-2"><select name="review_status" class="form-control"><option value="">Toda revisión</option>@foreach(\App\Models\Event::REVIEW_STATUS_LABELS as $v=>$l)<option value="{{ $v }}" @selected(request('review_status')===$v)>{{ $l }}</option>@endforeach</select></div>
<div class="col-md-2"><select name="status" class="form-control"><option value="">Toda publicación</option><option value="draft" @selected(request('status')==='draft')>Borrador</option><option value="published" @selected(request('status')==='published')>Publicado</option></select></div>
<div class="col-md-2"><input name="title" value="{{ request('title') }}" class="form-control" placeholder="Título"></div><div class="col-md-2"><input name="researcher" value="{{ request('researcher') }}" class="form-control" placeholder="Investigador"></div><div class="col-md-2"><button class="btn btn-primary">Filtrar</button></div>
<div class="col-md-3 mt-2"><input name="institution" value="{{ request('institution') }}" class="form-control" placeholder="Institución"></div><div class="col-md-3 mt-2"><input type="date" name="submitted_from" value="{{ request('submitted_from') }}" class="form-control"></div></form></div>
<div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Tipo / título</th><th>Investigador</th><th>Institución</th><th>Revisión</th><th>Publicación</th><th>Envío</th><th>Revisor</th><th>Actualización</th><th></th></tr></thead><tbody>
@forelse($submissions as $item) @php($m=$item['model'])<tr><td><span class="badge badge-light">{{ $item['label'] }}</span><br><strong>{{ $m->title }}</strong></td><td>{{ $m->author?->name }}</td><td>{{ $m->author?->subscription?->publicationInstitution() ?: '—' }}</td><td><span class="badge badge-info">{{ $m->reviewStatusLabel() }}</span></td><td>{{ $m->isPublished() ? 'Publicado' : 'Borrador' }}</td><td>{{ $m->submitted_at?->format('d/m/Y H:i') ?: '—' }}</td><td>{{ $m->reviewer?->name ?: '—' }}</td><td>{{ $m->updated_at->format('d/m/Y H:i') }}</td><td><a class="btn btn-sm btn-primary" href="{{ route('admin.submissions.show',[$item['type'],$m->id]) }}">Revisar</a></td></tr>@empty<tr><td colspan="9" class="text-center py-5">No hay aportes recibidos.</td></tr>@endforelse
</tbody></table></div>@if($submissions->hasPages())<div class="card-footer">{{ $submissions->links() }}</div>@endif</div></x-app-layout>
