<x-app-layout><x-slot name="header"><div class="d-flex justify-content-between"><div><h1 class="m-0">Revisión de aporte</h1><small>{{ ucfirst($type) }} · {{ $submission->title }}</small></div><a href="{{ route('admin.submissions.index') }}" class="btn btn-secondary">Volver</a></div></x-slot>
<div class="row"><div class="col-lg-8"><div class="card card-primary card-outline"><div class="card-header"><h3 class="card-title">Contenido enviado por un investigador</h3></div><div class="card-body">
<h3>{{ $submission->title }}</h3>@if($type==='research_publication')<p><strong>{{ $submission->publicationTypeLabel() }}</strong> · {{ $submission->year }} · {{ $submission->institution }}</p><p>{{ $submission->abstract }}</p><p><strong>Autores:</strong> {{ $submission->authors->pluck('author_name')->join(', ') }}</p><p><strong>DOI:</strong> {{ $submission->doi ?: '—' }} · <strong>Enlace:</strong> {{ $submission->external_url ?: '—' }} · <strong>PDF autorizado:</strong> {{ $submission->pdf_distribution_authorized?'Sí':'No' }}</p>@else @if($submission->summary)<p class="lead">{{ $submission->summary }}</p>@endif<div>{!! $submission->description !!}</div>@endif<hr>
@if($type==='event')<dl><dt>Fechas</dt><dd>{{ $submission->starts_at }} — {{ $submission->ends_at }}</dd><dt>Modalidad y lugar</dt><dd>{{ $submission->modalityLabel() }} · {{ $submission->location }}</dd><dt>Organización</dt><dd>{{ $submission->organizer }} · {{ $submission->responsible_name }}</dd><dt>Contacto</dt><dd>{{ $submission->contact_email }} {{ $submission->contact_phone }} {{ $submission->website_url }}</dd></dl>@elseif($type==='call')<dl><dt>Apertura y cierre</dt><dd>{{ $submission->opens_at }} — {{ $submission->closes_at }}</dd><dt>Inscripción</dt><dd>{{ $submission->registration_url }}</dd></dl>@endif
@php($hasFile=$type==='event' ? $submission->attachment_path : (in_array($type,['bulletin','research_publication']) ? $submission->pdf_path : $submission->bases_pdf_path))@if($hasFile)<a class="btn btn-outline-danger" href="{{ route('admin.submissions.download',[$type,$submission->id]) }}"><i class="fas fa-download"></i> Descargar archivo privado</a>@endif
<a class="btn btn-outline-primary" href="{{ $type==='research_publication' ? route('admin.research-publications.edit',$submission) : route('admin.'.$type.'s.edit',$submission) }}">Editar contenido</a>
</div></div><div class="card"><div class="card-header">Historial</div><div class="card-body"><ul class="timeline">@foreach($submission->reviewHistory as $h)<li class="mb-3"><strong>{{ $h->previous_status ?: 'Inicio' }} → {{ $h->new_status }}</strong><br>{{ $h->comments }}<small class="d-block text-muted">{{ $h->changedBy?->name ?: 'Sistema' }} · {{ $h->created_at->format('d/m/Y H:i') }}</small></li>@endforeach</ul></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-body"><p><strong>Miembro</strong><br>{{ $submission->author?->name }}<br>{{ $submission->author?->email }}<br>{{ $submission->author?->subscription?->publicationInstitution() }}<br>{{ $submission->author?->subscription?->primaryResearchArea() }}</p><p><strong>Revisión:</strong> {{ $submission->reviewStatusLabel() }}<br><strong>Publicación:</strong> {{ $submission->isPublished()?'Publicado':'Borrador' }}<br><strong>Revisor:</strong> {{ $submission->reviewer?->name ?: '—' }}</p>
@if($submission->isSubmittedForReview())<form method="POST" action="{{ route('admin.submissions.start-review',[$type,$submission->id]) }}">@csrf @method('PATCH')<button class="btn btn-primary btn-block">Iniciar revisión</button></form>@endif
@if($submission->isUnderReview())<form method="POST" action="{{ route('admin.submissions.observe',[$type,$submission->id]) }}" class="mt-2">@csrf @method('PATCH')<textarea name="review_notes" required minlength="10" maxlength="5000" class="form-control mb-2" placeholder="Observación"></textarea><button class="btn btn-warning btn-block">Observar</button></form><form method="POST" action="{{ route('admin.submissions.approve',[$type,$submission->id]) }}" class="mt-2">@csrf @method('PATCH')<textarea name="review_notes" maxlength="5000" class="form-control mb-2" placeholder="Nota opcional"></textarea><button class="btn btn-success btn-block">Aprobar</button></form><form method="POST" action="{{ route('admin.submissions.reject',[$type,$submission->id]) }}" class="mt-2">@csrf @method('PATCH')<textarea name="review_notes" required minlength="10" maxlength="5000" class="form-control mb-2" placeholder="Motivo del rechazo"></textarea><button class="btn btn-danger btn-block">Rechazar</button></form>@endif
@if($submission->isApprovedForPublication() && !$submission->isPublished())<form method="POST" action="{{ route('admin.submissions.publish',[$type,$submission->id]) }}">@csrf @method('PATCH')<button class="btn btn-success btn-block">Publicar</button></form>@elseif($submission->isApprovedForPublication() && $submission->isPublished())<form method="POST" action="{{ route('admin.submissions.unpublish',[$type,$submission->id]) }}">@csrf @method('PATCH')<button class="btn btn-warning btn-block">Despublicar</button></form>@endif
</div></div></div></div></x-app-layout>
