<x-app-layout>
    <x-slot name="header"><div class="d-flex justify-content-between align-items-center"><div><h1 class="m-0"><i class="far fa-calendar-alt text-primary mr-2"></i>Eventos</h1><small class="text-muted">Gestiona la información pública de actividades y encuentros.</small></div>@can('events.create')<a href="{{ route('admin.events.create') }}" class="btn btn-primary"><i class="fas fa-plus mr-1"></i> Crear evento</a>@endcan</div></x-slot>
    <div class="card card-primary card-outline">
        <div class="card-header"><form class="row"><div class="col-md-6"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Buscar evento"></div><div class="col-md-3"><select name="status" class="form-control"><option value="">Todos los estados</option><option value="draft" @selected(request('status') === 'draft')>Borradores</option><option value="published" @selected(request('status') === 'published')>Publicados</option></select></div><div class="col-md-3"><button class="btn btn-primary">Filtrar</button></div></form></div>
        <div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Evento</th><th>Fecha</th><th>Modalidad</th><th>Estado</th><th class="text-right">Acciones</th></tr></thead><tbody>
            @forelse($events as $item)<tr><td><strong>{{ $item->title }}</strong><small class="d-block text-muted">/eventos/{{ $item->slug }}</small></td><td><strong>{{ $item->starts_at->format('d/m/Y') }}</strong><small class="d-block text-muted">{{ $item->starts_at->format('H:i') }} - {{ $item->ends_at->format('d/m/Y H:i') }}</small></td><td>{{ $item->modalityLabel() }}</td><td><span class="badge badge-{{ $item->isPublished() ? 'success' : 'secondary' }}">{{ $item->isPublished() ? 'Publicado' : 'Borrador' }}</span></td><td class="text-right text-nowrap">@can('events.publish')<form method="POST" action="{{ $item->isPublished() ? route('admin.events.unpublish', $item) : route('admin.events.publish', $item) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $item->isPublished() ? 'secondary' : 'success' }}" title="{{ $item->isPublished() ? 'Despublicar' : 'Publicar' }}"><i class="fas fa-{{ $item->isPublished() ? 'eye-slash' : 'globe' }}"></i></button></form>@endcan @can('events.edit')<a href="{{ route('admin.events.edit', $item) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i></a>@endcan @can('events.delete')<form method="POST" action="{{ route('admin.events.destroy', $item) }}" class="d-inline" onsubmit="return confirm('¿Eliminar este evento?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form>@endcan</td></tr>
            @empty<tr><td colspan="5" class="text-center py-5">No hay eventos.</td></tr>@endforelse
        </tbody></table></div></div>
        @if($events->hasPages())<div class="card-footer">{{ $events->links() }}</div>@endif
    </div>
</x-app-layout>
