<?php
namespace App\Models;
use App\Models\Concerns\HasContentReview;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;
class ResearchPublication extends Model
{
 use HasContentReview;
 public const STATUS_DRAFT='draft'; public const STATUS_PUBLISHED='published';
 public const TYPE_SCIENTIFIC_ARTICLE='scientific_article'; public const TYPE_BOOK='book'; public const TYPE_BOOK_CHAPTER='book_chapter'; public const TYPE_CONFERENCE_PAPER='conference_paper'; public const TYPE_THESIS='thesis'; public const TYPE_TECHNICAL_REPORT='technical_report'; public const TYPE_RESEARCH_PROJECT='research_project'; public const TYPE_WORKING_PAPER='working_paper'; public const TYPE_SCIENTIFIC_POSTER='scientific_poster'; public const TYPE_OTHER='other';
 public const TYPE_LABELS=[self::TYPE_SCIENTIFIC_ARTICLE=>'Artículo científico',self::TYPE_BOOK=>'Libro',self::TYPE_BOOK_CHAPTER=>'Capítulo de libro',self::TYPE_CONFERENCE_PAPER=>'Ponencia',self::TYPE_THESIS=>'Tesis',self::TYPE_TECHNICAL_REPORT=>'Informe técnico',self::TYPE_RESEARCH_PROJECT=>'Proyecto de investigación',self::TYPE_WORKING_PAPER=>'Documento de trabajo',self::TYPE_SCIENTIFIC_POSTER=>'Póster científico',self::TYPE_OTHER=>'Otro'];
 public const LICENSE_LABELS=['all_rights_reserved'=>'Todos los derechos reservados','cc_by'=>'CC BY','cc_by_sa'=>'CC BY-SA','cc_by_nc'=>'CC BY-NC','cc_by_nc_sa'=>'CC BY-NC-SA','public_domain'=>'Dominio público','other'=>'Otra'];
 protected $fillable=['user_id','title','slug','abstract','publication_type','publication_date','year','research_area','research_line','institution','journal_name','publisher','volume','issue','pages','doi','issn','isbn','external_url','keywords','citation_text','pdf_path','pdf_original_name','pdf_mime_type','pdf_size','cover_image_id','pdf_distribution_authorized','pdf_public','license_type','seo_title','seo_description','origin','review_status','status','submitted_at','review_started_at','reviewed_at','reviewed_by','review_notes','published_at'];
 protected $casts=['publication_date'=>'date','keywords'=>'array','pdf_distribution_authorized'=>'boolean','pdf_public'=>'boolean','submitted_at'=>'datetime','review_started_at'=>'datetime','reviewed_at'=>'datetime','published_at'=>'datetime'];
 protected static function booted():void { static::deleting(fn($m)=>$m->pdf_path?Storage::disk('local')->delete($m->pdf_path):null); }
 public function author():BelongsTo{return $this->belongsTo(User::class,'user_id');} public function user():BelongsTo{return $this->author();} public function authors():HasMany{return $this->hasMany(ResearchPublicationAuthor::class)->orderBy('author_order');} public function coverImage():BelongsTo{return $this->belongsTo(MediaFile::class,'cover_image_id');}
 public function isDraft():bool{return $this->isReviewDraft();} public function isSubmitted():bool{return $this->isSubmittedForReview();} public function isApproved():bool{return $this->isApprovedForPublication();} public function isRejected():bool{return $this->review_status===self::REVIEW_REJECTED;} public function isPublished():bool{return $this->status===self::STATUS_PUBLISHED&&$this->published_at!==null;} public function hasPdf():bool{return filled($this->pdf_path);} public function hasExternalAccess():bool{return filled($this->doi)||filled($this->external_url);} public function canExposePdfPublicly():bool{return $this->isPublished()&&$this->isApproved()&&$this->pdf_public&&$this->pdf_distribution_authorized&&$this->hasPdf();} public function isExternalOnly():bool{return !$this->hasPdf()&&$this->hasExternalAccess();}
 public function scopePubliclyVisible(Builder $q):Builder{return $q->where('review_status',self::REVIEW_APPROVED)->where('status',self::STATUS_PUBLISHED)->whereNotNull('published_at');} public function scopePendingReview(Builder $q):Builder{return $q->whereIn('review_status',[self::REVIEW_SUBMITTED,self::REVIEW_UNDER_REVIEW]);} public function scopeOwnedBy(Builder $q,$user):Builder{return $q->where('user_id',is_object($user)?$user->id:$user);} public function scopeByYear(Builder $q,$year):Builder{return $q->when($year,fn($x)=>$x->where('year',$year));} public function scopeByType(Builder $q,$type):Builder{return $q->when($type,fn($x)=>$x->where('publication_type',$type));} public function scopeByResearchArea(Builder $q,$area):Builder{return $q->when($area,fn($x)=>$x->where('research_area',$area));} public function scopeByResearchLine(Builder $q,$line):Builder{return $q->when($line,fn($x)=>$x->where('research_line',$line));} public function scopeByInstitution(Builder $q,$institution):Builder{return $q->when($institution,fn($x)=>$x->where('institution',$institution));}
 public function scopeSearch(Builder $q,?string $term):Builder{return $q->when($term,fn($x)=>$x->where(function($s)use($term){$like='%'.$term.'%';$s->where('title','like',$like)->orWhere('abstract','like',$like)->orWhere('doi','like',$like)->orWhere('institution','like',$like)->orWhere('journal_name','like',$like)->orWhere('keywords','like','%'.mb_strtolower($term).'%')->orWhereHas('authors',fn($a)=>$a->where('author_name','like',$like));}));}
 public function publicationTypeLabel():string{return self::TYPE_LABELS[$this->publication_type]??'Otro';}
 public function suggestedCitation():string { if($this->citation_text)return $this->citation_text; $authors=$this->authors->pluck('author_name')->join(', '); return trim($authors.'. '.($this->year?'('.$this->year.'). ':'').$this->title.'. '.($this->journal_name?:$this->publisher).($this->doi?' https://doi.org/'.$this->doi:'')); }
}
