<div class="form-group"><label>Título <span class="text-danger">*</span></label><input name="title" class="form-control" required value="{{ old('title', $news->title ?? '') }}"></div>
<div class="form-group"><label>Slug</label><div class="input-group"><div class="input-group-prepend"><span class="input-group-text">/noticias/</span></div><input name="slug" class="form-control" value="{{ old('slug', $news->slug ?? '') }}" placeholder="Se genera desde el título"></div></div>
<div class="form-group"><label>Extracto</label><textarea name="excerpt" maxlength="500" rows="3" class="form-control">{{ old('excerpt', $news->excerpt ?? '') }}</textarea></div>
<div class="row">
    <div class="form-group col-md-6"><label>Categoría</label><select name="category_id" class="form-control"><option value="">Sin categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('category_id', $news->category_id ?? 0) === $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="form-group col-md-6"><label>Imagen destacada</label><select name="featured_image_id" class="form-control"><option value="">Sin imagen</option>@foreach($mediaImages as $image)<option value="{{ $image->id }}" @selected((int) old('featured_image_id', $news->featured_image_id ?? 0) === $image->id)>{{ $image->original_name }}</option>@endforeach</select></div>
</div>
<div class="form-group"><label>Etiquetas</label><select name="tags[]" class="form-control" multiple size="5">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array($tag->id, old('tags', isset($news) ? $news->tags->pluck('id')->all() : [])))>{{ $tag->name }}</option>@endforeach</select><small class="text-muted">Usa Ctrl o Cmd para elegir varias.</small></div>
<div class="form-group"><label>Contenido <span class="text-danger">*</span></label><textarea name="content" rows="18" required class="form-control page-content-editor" data-image-list-url="{{ route('admin.media-files.editor.images') }}" data-image-upload-url="{{ route('admin.media-files.editor.upload') }}">{{ old('content', $news->content ?? '') }}</textarea></div>
<div class="custom-control custom-checkbox mb-4"><input type="hidden" name="is_featured" value="0"><input type="checkbox" class="custom-control-input" id="is_featured" name="is_featured" value="1" @checked(old('is_featured', $news->is_featured ?? false))><label class="custom-control-label" for="is_featured">Destacar noticia</label></div>
<div class="card card-outline card-info"><div class="card-header"><h3 class="card-title"><i class="fas fa-search mr-2"></i>SEO individual</h3></div><div class="card-body">
    <div class="form-group"><label>Meta título</label><input name="seo_title" maxlength="60" class="form-control" value="{{ old('seo_title', $news->seo_title ?? '') }}" placeholder="Si queda vacío se usará el título de la noticia"></div>
    <div class="form-group"><label>Meta descripción</label><textarea name="seo_description" maxlength="160" rows="2" class="form-control" placeholder="Si queda vacío se usará el extracto">{{ old('seo_description', $news->seo_description ?? '') }}</textarea></div>
    <div class="form-group"><label>Palabras clave</label><input name="seo_keywords" maxlength="500" class="form-control" value="{{ old('seo_keywords', $news->seo_keywords ?? '') }}" placeholder="Si queda vacío se usarán las etiquetas"></div>
    <div class="form-group mb-0"><label>Indexación</label><select name="seo_index" class="form-control"><option value="1" @selected((string) old('seo_index', isset($news) ? (int) $news->seo_index : 1) === '1')>Indexar</option><option value="0" @selected((string) old('seo_index', isset($news) ? (int) $news->seo_index : 1) === '0')>No indexar</option></select></div>
</div></div>

<div class="modal fade" id="page-media-library-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="far fa-images mr-2"></i>Biblioteca multimedia RIMIS</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row" id="page-media-library-grid"></div><div class="text-center py-5 d-none" id="page-media-library-empty">No hay imágenes activas disponibles.</div></div></div></div></div>
